Api tests roop sprint19
meshlink/meshlink pull request #53
Opened 2018-10-03 10:56 UTC by sairoop-elear

2018-10-04 13:20 UTC, gsliepen requested changes
That's a large pull request! In the future, it's definitely better to have smaller and more frequent pulls than infrequent big ones.

2018-10-04 13:20 UTC, gsliepen commented on .gitignore
> +<<<<<<< Updated upstream
It seems a merge conflict was not resolved here.

2018-10-04 13:20 UTC, gsliepen commented on .gitmodules
> +	url = https://github.com/elear-solutions/catta.git
The pull request should not change the submodules to a different repository.

2018-10-04 13:20 UTC, gsliepen commented on src/conf.c
> +	if (snprintf(filename, sizeof(filename), "%s" SLASH "hosts" SLASH "%s", mesh->confbase, name) >= PATH_MAX) {
Use `sizeof(filename)` instead of `PATH_MAX`, so it matches the second argument of `snprintf()`.

2018-10-04 13:20 UTC, gsliepen commented on src/conf.c
> +	if (snprintf(tmpname, sizeof(tmpname), "%s.tmp", filename) >= PATH_MAX) {
The same here: `sizeof(tmpname)` instead of `PATH_MAX`.

2018-10-04 13:20 UTC, gsliepen commented on src/discovery.c
> +  /*<ES_mod>
Please remove all occurences of `<ES_mod>`. Git will track who/when the code was modified, so there is no need to add tags like this to the code.

2018-10-04 13:20 UTC, gsliepen commented on src/meshlink.c
> +  if(s->sa.sa.sa_family == AF_INET) {
The indentation is incorrect here. Run `make astyle` for the top of the source tree to have everything automatically formatted.

2018-10-04 13:20 UTC, gsliepen commented on src/meshlink.c
> +      perror("Could not send a UDP packet to ourself :");
Remove the call to `perror()`, all logging should be done via `logger()` only.

2018-10-04 13:20 UTC, gsliepen commented on src/meshlink.c
> +		if (snprintf(invname, sizeof(invname), "%s" SLASH "%s", filename, ent->d_name) >= PATH_MAX) {
`sizeof(invname)` instead of `PATH_MAX`

2018-10-04 13:20 UTC, gsliepen commented on src/net_packet.c
> +  if(sa->sa.sa_family == AF_INET) {
Why was this if statement added? This will prevent IPv6 from working.

2018-10-04 13:20 UTC, gsliepen commented on src/meshlink.h
> -	MESHLINK_EPEER, ///< A peer caused an error
Keep the `,` at the last entry, this makes it easier to add entries later.

2018-10-04 13:20 UTC, gsliepen commented on src/meshlink.h
> -	MESHLINK_CRITICAL, ///< Critical errors which cause MeshLink to fail completely.
Same here.

2018-10-04 13:20 UTC, gsliepen commented on src/net_socket.c
> +#include <sys/socket.h>
This line should not be necessary: `<sys/socket.h>` is included via `system.h` (which in turn includes `have.h`).

2018-10-04 13:20 UTC, gsliepen commented on src/splay_tree.c
> +	splay_node_t left = SPLAY_NODE_T_INIT, right = SPLAY_NODE_T_INIT;
Instead of `SPLAY_NODE_T_INIT`, just write `{0}`, this is valid C99 and even MSVC should handle that.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/Makefile.am
> +<<<<<<< HEAD
Merge conflicts.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/common_handlers.c
> +    execute_close();
It's dangerous to do system calls or anything that might allocate memory from a signal handler. I would be much better to just set a flag and have the main thread react to it, or if this is going to run on Linux only, use `signalfd()` to create a filedescriptor than can be read to receive signals.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/common_handlers.c
> +    memset(&req_if, 0, sizeof(req_if));
Write `struct ifreq req_if = {0}` instead of using `memset()`. It's shorter to write and less chance of making mistakes. The same goes for the other calls to `memset()`.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/common_handlers.c
> +    strncpy(req_if.ifr_name, if_name, IFNAMSIZ - 1);
The `- 1` must be removed here.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/common_handlers.c
> +    strncpy(req_if.ifr_name, if_name, IFNAMSIZ - 1);
Same here, `- 1` must be removed.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/common_handlers.c
> +void start_nw_intf(const char *if_name) {
This is a lot of code that does Linux-specific `ioctl()`-calls to configure the network. And it's all going to break down when you want to do something more complex than just bringing a network up/down with a single IP address and netmask. While I wouldn't normally recommend using `system()`, I think here it is just better to construct a commandline that calls ifconfig with the right parameters, and execute that using `system()`.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/containers.h
> +struct lxc_container *find_container(char *name);
I think most of the `char *` parameters can be made `const char *`.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/mesh_event_handler.c
> +static uint16_t ec_byte_stream_to_uint16(const uint8_t *byte_stream) {
You should use `noths()` and `htons()` to convert to/from network endianness. Twenty years ago code like this was necessary, but nowadays you can assume that all your software is running on little endian processors, so these functions should not be necessary at all.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/mesh_event_handler.c
> +  char *ip = (char *) malloc(strlen(import) + 1);
Use `char *ip = strdup(import);` instead of `malloc()`+`strcpy()`.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/mesh_event_handler.c
> +  fprintf(stderr, "Socket created and exported the IP address & port successfully\n");
Debug print statements must be removed before the code can be merged.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/common/mesh_event_handler.c
> +/*
Commented out code must be removed before it can be merged.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/gen_invite
> +#! /bin/bash
This is an automatically generated file, it should not be committed to git.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/execute_tests.c
> +    printf("Setting up Containers\n");
Should this not be `PRINT_TEST_CASE_MSG()`? If it's a debug statement, it should be removed, or at least printed to `stderr`.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_add_addr.c
> + * @license   To any person (the "Recipient") obtaining a copy of this software and
Code pushed to a public GitHub repository must have an open source license. Also, if this code is to be merged with the master branch of MeshLink, it must use be under the GPL-2+, and not have any copyright notices other than `Guus Sliepen <guus@meshlink.io>`.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_add_addr.c
> +    /* test_case_name = */ "test_case_mesh_add_address_01",
Instead of using comments, write: `.test_case_name = "test_case_mesh_address_01",`, and so on. Also, any members that are `0`, `NULL` or `false` don't have to be explicitly initialized.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_channel_get_flags.c
> +  sleep(1);
These `sleep(1)` statements should not be necessary. If they are, it is a bug in MeshLink.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_channel_get_flags.c
> +    meshlink_channel_close(mesh_handle, channel);
It should be OK to call `meshlink_close()` without calling `meshlink_channel_close()` and `meshlink_stop()` first; the close function will clean up everything.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_channel_set_poll_cb.c
> +  if(meshlink_errno == MESHLINK_EINVAL) {
Why don't we just do `assert(meshlink_errno == MESHLINK_EINVAL)`? We already use asserts everywhere in the code.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_channel_set_receive_cb.c
> +  for(int i = 0; i < 20; i++) {
Instead of polling every second, it is easier and faster to use condition variables, and replace these loops with calls to `pthread_cond_timedwait()`.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_default_blacklist.c
> +		fprintf(stderr, "Received invalid data from %s\n", src->name);
If we receive invalid data, we should exit with an error somehow. Maybe just call `assert(len)` here?

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_export.c
> +  meshlink_stop(mesh_handle);
`meshlink_start()` was not called so there is no need for `meshlink_stop()`.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/test_case_join_01/test/.libs/libcatta.la
> +# libcatta.la - a libtool library file
All these files in .libs directories should not be committed to git.

2018-10-04 13:20 UTC, gsliepen commented on test/blackbox/util/lxc_rename.sh
> +mv ${lxcpath}/${oldname} ${lxcpath}/${newname}
You can use `lxc-copy -R` to rename LXC containers.

2018-10-04 13:20 UTC, gsliepen commented on test/channels-cornercases.c
> +	struct sync_flag channel_opened = {.flag = false};
Use `{0}` instead.

2018-10-04 13:20 UTC, gsliepen commented on test/run_blackbox_tests.sh
> +meshlinkrootpath="/home/sairoop/meshlink"
This file is specific to Sai Roop's machine. They should be removed. It might be better if this script can read the appropriate values from a config file, so the script can be in git and doesn't have to be changed. A simple way is just to make this script `source` another file.

2018-10-09 05:35 UTC, sairoop-elear commented on test/blackbox/run_blackbox_tests/test_cases_channel_set_poll_cb.c
> +  if(meshlink_errno == MESHLINK_EINVAL) {
Actually these sort of test cases that I wrote was for testing invalid cases when NULL arguments are passed to the API, I hope if(meshlink_errno == MESHLINK_EINVAL) says whether test case is success or failed but if I use assert() it immediately suspends the execution. Is this a wrong way?

2018-10-09 06:29 UTC, gsliepen commented
On Tue, Oct 09, 2018 at 05:36:00AM +0000, sairoop-elear wrote:

> sairoop-elear commented on this pull request.
> 
> > +  PRINT_TEST_CASE_MSG("meshlink_open status: %s\n", meshlink_strerror(meshlink_errno));
> +  assert(mesh_handle);
> +
> +  meshlink_set_log_cb(mesh_handle, TEST_MESHLINK_LOG_LEVEL, meshlink_callback_logger);
> +  meshlink_set_node_status_cb(mesh_handle, meshlink_callback_node_status);
> +	meshlink_set_channel_accept_cb(mesh_handle, channel_accept);
> +  PRINT_TEST_CASE_MSG("starting mesh\n");
> +  assert(meshlink_start(mesh_handle));
> +
> +  meshlink_node_t *node = meshlink_get_self(mesh_handle);
> +  assert(node != NULL);
> +
> +  PRINT_TEST_CASE_MSG("Setting poll cb\n");
> +  meshlink_set_channel_poll_cb(mesh_handle, NULL, channel_poll);
> +
> +  if(meshlink_errno == MESHLINK_EINVAL) {
> 
> Actually these sort of test cases that I wrote was for testing invalid cases when NULL arguments are passed to the API, I hope if(meshlink_errno == MESHLINK_EINVAL) says whether test case is success or failed but if I use assert() it immediately suspends the execution. Is this a wrong way? 

Well, it's not wrong, but I don't see why one error is treated
specially. Bugs can happen anywhere, they are not going to always be
exactly where you put the if-statement, they can also trigger the
asserts. If cmocka gives different results depending on if we check
something with assert() or with the if-statements, then that is a
problem. Maybe instead of libc's assert() the assert macros from cmocka
should be used instead?

https://api.cmocka.org/group__cmocka__asserts.html

And then you can also just write assert_int_equal(meshlink_errno, MESHLINK_EINVAL)
in the above case.

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

2018-10-11 09:17 UTC, sairoop-elear commented on test/blackbox/common/common_handlers.c
> +    execute_close();
Can you brief this a little bit more about this

2018-10-11 09:19 UTC, sairoop-elear commented on test/blackbox/util/lxc_rename.sh
> +mv ${lxcpath}/${oldname} ${lxcpath}/${newname}
I've tried using `lxc-copy -n oldname -N newname -R` but the issue is it's renaming only if the container has no snapshots and if it has any snapshots then it's returning error code no - 256

2018-10-11 09:30 UTC, sairoop-elear commented on test/blackbox/run_blackbox_tests/test_cases_channel_get_flags.c
> +  sleep(1);
In most of the cases where If I'm using `meshlink_send( )` before that & after `meshlink_start( )` it needs such `sleep( )` . Also when to receive data itself or after exporting & importing etc., if didn't place some `sleep( )` it's failing.

2018-10-11 17:36 UTC, gsliepen commented on test/blackbox/common/common_handlers.c
> +    execute_close();
Yes: only a subset of function calls is safe to perform while inside a signal handler, see: http://man7.org/linux/man-pages/man7/signal-safety.7.html. The function `execute_close()` calls `meshlink_close()`, which calls many functions that are not in the list of safe functions.

In many test cases, I see the pattern: `setup_signals(); ...; execute_start(); while(1) select(...);`. So instead of calling `execute_close()` inside the signal handler, just set a global variable, say `test_running`, to `true`, and immediately return. Then inside `main()`, replace the while loop with: `while(test_running) pause(); execute_close();`.

2018-10-11 17:37 UTC, gsliepen commented on test/blackbox/util/lxc_rename.sh
> +mv ${lxcpath}/${oldname} ${lxcpath}/${newname}
Ah, I didn't know that, then the `mv` is fine.

2018-10-11 17:41 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_channel_get_flags.c
> +  sleep(1);
Ah, for `meshlink_send()` that's probably true, but not for `meshlink_channel_send()`.

2018-10-11 17:42 UTC, gsliepen commented on test/blackbox/run_blackbox_tests/test_cases_channel_get_flags.c
> +  sleep(1);
And this particular test doesn't call any send function at all.

2018-11-02 11:46 UTC, closed without merging